/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c_java_Main */

#ifndef _Included_c_java_Main
#define _Included_c_java_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_java_Main
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_c_1java_Main_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
